apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  # Use the locally built image loaded into kind by bootstrap.sh
  - name: docker.io/ahmed3sjsu/user-service
    newName: user-service
    newTag: "7fee733"
